config/routes.rb
Rails.application.routes.draw do
    root 'posts#index'
    resources :posts do
        member do
            put "like", to:"posts#upvote"
            put "unlike", to:"posts#downvote"
        end
        resources :comments
    end
     devise_for :users, controllers: {                                                                                         sessions: 'users/sessions',
         registrations: 'users/registrations'
         }                             
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_attached_file :image, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_many :comments
    acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_filter :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:rol, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:rol, :email, :password,:current_password) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name,:body))
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def post_params
        params.require(:post).permit(:description,:image)
    end
    
  def new
      @post = Post.new
  end

  def index
      @posts = Post.all
  end
    
  def show
      @post = Post.find(params[:id])
  end
    
    def upvote
        @post = Post.find(params[:id])
        @post.upvote_from current_user
        redirect_to post_path(@post)
    end
    
    def downvote
        @post = Post.find(params[:id])
        @post.downvote_from current_user
        redirect_to post_path(@post)
    end
    
    def create
        @post= Post.new(post_params)
        if @post.save
            flash[:success] = "Su foto ha sido publicada"
            redirect_to post_path(@post)
        else
            flash[:error] = @post.errors.full_messages
            redirect_to new_post_path
        end
    end
    
def update
    respond_to do |format|
        @post = Post.find(params[:id])
        if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
def edit
        @post = Post.find(params[:id])
    end

def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def permit_post
        params.require(:post).permit(:image,:description)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><p>Nombre: <%=comment.name %></p></h3>
  </div>
  <div class="panel-body">
<%=comment.body %>
 <p>Hace: <%=time_ago_in_words(comment.created_at) %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
<p>
    <%=f.label :Nombre %>
    <%=f.text_field :name,class:"form-control"%>
</p>
<p>
    <%=f.label :Descripcion %>
    <br>
    <%=f.text_area :body,class:"form-control" %>
</p>
<br>
<p>
    <%=f.submit class:"btn btn-default" %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<style>
body{
    background: url("/presence-ii.png");
    
        
}
    </style>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Galeria</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-bare/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--a class="navbar-brand" href="#">Inicio</a-->
                <%= link_to "Galeria", root_url, class: "navbar-brand"%>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                    <%- if current_user %>
                       <li>
                        <%= link_to "Nueva Imagen", new_post_path%>
                    </li>
                       <li>
                           <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete%>
                    </li>
                       <li>
                           <%= link_to current_user.email,edit_user_registration_path %> 
                       </li>
                        <% else %>
                        <li>
                            <%= link_to "Iniciar Sesion", new_user_session_path %>
                        </li>
                        <li>
                            <%= link_to "Registrate", new_user_registration_path %>
                        </li>
                        <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <% flash.each do |a , b| %>
                   <div class="alert alert-success"><%= b %></div>
                <% end %>
                    <%= yield %>
            </div>
        </div>

    </div>
</body>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :description, class:"form-control" %>
  </div>
  <div class="field">
      <%= f.label :Imagen %>
<%= f.file_field :image,class:"btn btn-default btn-file" %>
  </div>

  <div class="actions">
      <%= f.submit "Guardar cambios",class:"btn btn-default" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%= button_to "delete", @post, :method => :delete ,class:"btn btn-danger"%>

app/views/posts/index.html.erb
<h2>Todas las imagenes</h2>
<% @posts.each do |x| %>
<div class="white">
   <br>
    <%= image_tag x.image.url(:original), size:"500" %>
    <br>
    <%= x.description %>
    <br>
    <a href="posts/<%= x.id %>" class="btn btn-info" role="button">ver imagen</a>
    <br>
    <%- if current_user %>
    <%- if current_user.rol== "Administrador" %>
    <br>
    <a href="/posts/<%= x.id %>/edit" class="btn btn-info" role="button">editar imagen</a>
    <% end %>
    <% end %>
</div>
<% end %>

app/views/posts/new.html.erb
<h2>Adelante, sube una nueva imagen :D</h2>
<%= form_for @post,html:{ multipart: true } do |f| %>
<%= f.label :Imagen %>
<%= f.file_field :image,class:"btn btn-default btn-file" %>
<br>
<%= f.label :descripcion %>
<%= f.text_area :description, class:"form-control" %>
<br>
<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= image_tag @post.image.url(:original) %>
<br>
<%= @post.description %>
<div class = "panel panel-default">
   <div class = "panel-heading">Panel Heading</div>
   
   
   <table class = "table">
      <tr>
         <td>Likes</td>
         <td><%=@post.get_upvotes.size%></td>
         <%- if current_user %>
         <td><%= button_to 'Like', like_post_path(@post), method: :put, class:"btn btn-primary btn-info"%></td>
          <%end%>
      </tr>
      
      <tr>
         <td>Dislikes</td>
         <td><%=@post.get_downvotes.size%></td>
         <%- if current_user %>
         <td><%= button_to 'Dislike', unlike_post_path(@post), method: :put, class:"btn btn-primary btn-info"%></td>
          <%end%>
      </tr>
   </table>
</div>


<h2><%= @post.comments.count%> Comentarios</h2>
<%= render @post.comments %>
<%- if current_user %>

<h3>Añada un comentario:</h3>
<%= render 'comments/form' %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>